DefaultContentLanguage = "ja"

baseURL = "https://blog.lespaulstudioplus.info/"
languageCode = "ja-jp"
title = "blog.lespaulstudioplus.info"
theme = "hugo-clarity"

[params]
numberOfTagsShown = 14
author = "Machi Hoshino"
introDescription = "Unofficial technical blog mainly around VMware Tanzu"
mobileNavigation = "left"
ga_analytics = "G-E3KCXZWE52"

[deployment]
order = [".jpg$", ".gif$"]
[[deployment.targets]]
# An arbitrary name for this target.
name = "lespaulstudioplus"
URL = "s3://blog.lespaulstudioplus.info?region=ap-northeast-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true # change to false to disable inclusion of rawHTML and math functions
    xhtml = false
